/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSplatRouteImport } from './routes/_public/$'
import { Route as PublicLandingPathRouteImport } from './routes/_public/$landingPath'
import { Route as PublicAlgemeneVoorwaardenRouteImport } from './routes/_public/algemene-voorwaarden'
import { Route as PublicBedanktRouteImport } from './routes/_public/bedankt'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicCookiesRouteImport } from './routes/_public/cookies'
import { Route as PublicGratisWebsiteAnalyseRouteImport } from './routes/_public/gratis-website-analyse'
import { Route as PublicOverOnsRouteImport } from './routes/_public/over-ons'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicReviewsRouteImport } from './routes/_public/reviews'
import { Route as PublicSeoEnkhuizenRouteImport } from './routes/_public/seo-enkhuizen'
import { Route as PublicStartJeProjectRouteImport } from './routes/_public/start-je-project'
import { Route as PublicTaxiWebsiteLatenMakenRouteImport } from './routes/_public/taxi-website-laten-maken'
import { Route as PublicWebdesignBureauRouteImport } from './routes/_public/webdesign-bureau'
import { Route as PublicWebsiteLatenMakenRouteImport } from './routes/_public/website-laten-maken'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as PublicBlogIndexRouteImport } from './routes/_public/blog/index'
import { Route as PublicBlogSlugRouteImport } from './routes/_public/blog/$slug'
import { Route as PublicDienstenIndexRouteImport } from './routes/_public/diensten/index'
import { Route as PublicDienstenECommerceRouteImport } from './routes/_public/diensten/e-commerce'
import { Route as PublicDienstenWebshopsRouteImport } from './routes/_public/diensten/webshops'
import { Route as PublicDienstenWebsiteOpMaatRouteImport } from './routes/_public/diensten/website-op-maat'
import { Route as PublicPortfolioIndexRouteImport } from './routes/_public/portfolio/index'
import { Route as PublicPortfolioSlugRouteImport } from './routes/_public/portfolio/$slug'
import { Route as PublicRegioSlugRouteImport } from './routes/_public/regio/$slug'
import { Route as PublicWerkgebiedIndexRouteImport } from './routes/_public/werkgebied/index'
import { Route as PublicWerkgebiedSlugRouteImport } from './routes/_public/werkgebied/$slug'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSplatRoute = PublicSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLandingPathRoute = PublicLandingPathRouteImport.update({
  id: '/$landingPath',
  path: '/$landingPath',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAlgemeneVoorwaardenRoute =
  PublicAlgemeneVoorwaardenRouteImport.update({
    id: '/algemene-voorwaarden',
    path: '/algemene-voorwaarden',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicBedanktRoute = PublicBedanktRouteImport.update({
  id: '/bedankt',
  path: '/bedankt',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCookiesRoute = PublicCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGratisWebsiteAnalyseRoute =
  PublicGratisWebsiteAnalyseRouteImport.update({
    id: '/gratis-website-analyse',
    path: '/gratis-website-analyse',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicOverOnsRoute = PublicOverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicReviewsRoute = PublicReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSeoEnkhuizenRoute = PublicSeoEnkhuizenRouteImport.update({
  id: '/seo-enkhuizen',
  path: '/seo-enkhuizen',
  getParentRoute: () => PublicRoute,
} as any)
const PublicStartJeProjectRoute = PublicStartJeProjectRouteImport.update({
  id: '/start-je-project',
  path: '/start-je-project',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTaxiWebsiteLatenMakenRoute =
  PublicTaxiWebsiteLatenMakenRouteImport.update({
    id: '/taxi-website-laten-maken',
    path: '/taxi-website-laten-maken',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicWebdesignBureauRoute = PublicWebdesignBureauRouteImport.update({
  id: '/webdesign-bureau',
  path: '/webdesign-bureau',
  getParentRoute: () => PublicRoute,
} as any)
const PublicWebsiteLatenMakenRoute = PublicWebsiteLatenMakenRouteImport.update({
  id: '/website-laten-maken',
  path: '/website-laten-maken',
  getParentRoute: () => PublicRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDienstenIndexRoute = PublicDienstenIndexRouteImport.update({
  id: '/diensten/',
  path: '/diensten/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDienstenECommerceRoute = PublicDienstenECommerceRouteImport.update({
  id: '/diensten/e-commerce',
  path: '/diensten/e-commerce',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDienstenWebshopsRoute = PublicDienstenWebshopsRouteImport.update({
  id: '/diensten/webshops',
  path: '/diensten/webshops',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDienstenWebsiteOpMaatRoute =
  PublicDienstenWebsiteOpMaatRouteImport.update({
    id: '/diensten/website-op-maat',
    path: '/diensten/website-op-maat',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicPortfolioIndexRoute = PublicPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPortfolioSlugRoute = PublicPortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegioSlugRoute = PublicRegioSlugRouteImport.update({
  id: '/regio/$slug',
  path: '/regio/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicWerkgebiedIndexRoute = PublicWerkgebiedIndexRouteImport.update({
  id: '/werkgebied/',
  path: '/werkgebied/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicWerkgebiedSlugRoute = PublicWerkgebiedSlugRouteImport.update({
  id: '/werkgebied/$slug',
  path: '/werkgebied/$slug',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/$': typeof PublicSplatRoute
  '/$landingPath': typeof PublicLandingPathRoute
  '/algemene-voorwaarden': typeof PublicAlgemeneVoorwaardenRoute
  '/bedankt': typeof PublicBedanktRoute
  '/contact': typeof PublicContactRoute
  '/cookies': typeof PublicCookiesRoute
  '/gratis-website-analyse': typeof PublicGratisWebsiteAnalyseRoute
  '/over-ons': typeof PublicOverOnsRoute
  '/privacy': typeof PublicPrivacyRoute
  '/reviews': typeof PublicReviewsRoute
  '/seo-enkhuizen': typeof PublicSeoEnkhuizenRoute
  '/start-je-project': typeof PublicStartJeProjectRoute
  '/taxi-website-laten-maken': typeof PublicTaxiWebsiteLatenMakenRoute
  '/webdesign-bureau': typeof PublicWebdesignBureauRoute
  '/website-laten-maken': typeof PublicWebsiteLatenMakenRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/diensten/e-commerce': typeof PublicDienstenECommerceRoute
  '/diensten/webshops': typeof PublicDienstenWebshopsRoute
  '/diensten/website-op-maat': typeof PublicDienstenWebsiteOpMaatRoute
  '/portfolio/$slug': typeof PublicPortfolioSlugRoute
  '/regio/$slug': typeof PublicRegioSlugRoute
  '/werkgebied/$slug': typeof PublicWerkgebiedSlugRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/diensten/': typeof PublicDienstenIndexRoute
  '/portfolio/': typeof PublicPortfolioIndexRoute
  '/werkgebied/': typeof PublicWerkgebiedIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof PublicSplatRoute
  '/$landingPath': typeof PublicLandingPathRoute
  '/algemene-voorwaarden': typeof PublicAlgemeneVoorwaardenRoute
  '/bedankt': typeof PublicBedanktRoute
  '/contact': typeof PublicContactRoute
  '/cookies': typeof PublicCookiesRoute
  '/gratis-website-analyse': typeof PublicGratisWebsiteAnalyseRoute
  '/over-ons': typeof PublicOverOnsRoute
  '/privacy': typeof PublicPrivacyRoute
  '/reviews': typeof PublicReviewsRoute
  '/seo-enkhuizen': typeof PublicSeoEnkhuizenRoute
  '/start-je-project': typeof PublicStartJeProjectRoute
  '/taxi-website-laten-maken': typeof PublicTaxiWebsiteLatenMakenRoute
  '/webdesign-bureau': typeof PublicWebdesignBureauRoute
  '/website-laten-maken': typeof PublicWebsiteLatenMakenRoute
  '/admin/$': typeof AdminSplatRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/diensten/e-commerce': typeof PublicDienstenECommerceRoute
  '/diensten/webshops': typeof PublicDienstenWebshopsRoute
  '/diensten/website-op-maat': typeof PublicDienstenWebsiteOpMaatRoute
  '/portfolio/$slug': typeof PublicPortfolioSlugRoute
  '/regio/$slug': typeof PublicRegioSlugRoute
  '/werkgebied/$slug': typeof PublicWerkgebiedSlugRoute
  '/blog': typeof PublicBlogIndexRoute
  '/diensten': typeof PublicDienstenIndexRoute
  '/portfolio': typeof PublicPortfolioIndexRoute
  '/werkgebied': typeof PublicWerkgebiedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/$': typeof PublicSplatRoute
  '/_public/$landingPath': typeof PublicLandingPathRoute
  '/_public/algemene-voorwaarden': typeof PublicAlgemeneVoorwaardenRoute
  '/_public/bedankt': typeof PublicBedanktRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/cookies': typeof PublicCookiesRoute
  '/_public/gratis-website-analyse': typeof PublicGratisWebsiteAnalyseRoute
  '/_public/over-ons': typeof PublicOverOnsRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/reviews': typeof PublicReviewsRoute
  '/_public/seo-enkhuizen': typeof PublicSeoEnkhuizenRoute
  '/_public/start-je-project': typeof PublicStartJeProjectRoute
  '/_public/taxi-website-laten-maken': typeof PublicTaxiWebsiteLatenMakenRoute
  '/_public/webdesign-bureau': typeof PublicWebdesignBureauRoute
  '/_public/website-laten-maken': typeof PublicWebsiteLatenMakenRoute
  '/admin/$': typeof AdminSplatRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/_public/diensten/e-commerce': typeof PublicDienstenECommerceRoute
  '/_public/diensten/webshops': typeof PublicDienstenWebshopsRoute
  '/_public/diensten/website-op-maat': typeof PublicDienstenWebsiteOpMaatRoute
  '/_public/portfolio/$slug': typeof PublicPortfolioSlugRoute
  '/_public/regio/$slug': typeof PublicRegioSlugRoute
  '/_public/werkgebied/$slug': typeof PublicWerkgebiedSlugRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/_public/diensten/': typeof PublicDienstenIndexRoute
  '/_public/portfolio/': typeof PublicPortfolioIndexRoute
  '/_public/werkgebied/': typeof PublicWerkgebiedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$landingPath'
    | '/algemene-voorwaarden'
    | '/bedankt'
    | '/contact'
    | '/cookies'
    | '/gratis-website-analyse'
    | '/over-ons'
    | '/privacy'
    | '/reviews'
    | '/seo-enkhuizen'
    | '/start-je-project'
    | '/taxi-website-laten-maken'
    | '/webdesign-bureau'
    | '/website-laten-maken'
    | '/admin/$'
    | '/admin/'
    | '/blog/$slug'
    | '/diensten/e-commerce'
    | '/diensten/webshops'
    | '/diensten/website-op-maat'
    | '/portfolio/$slug'
    | '/regio/$slug'
    | '/werkgebied/$slug'
    | '/blog/'
    | '/diensten/'
    | '/portfolio/'
    | '/werkgebied/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/$landingPath'
    | '/algemene-voorwaarden'
    | '/bedankt'
    | '/contact'
    | '/cookies'
    | '/gratis-website-analyse'
    | '/over-ons'
    | '/privacy'
    | '/reviews'
    | '/seo-enkhuizen'
    | '/start-je-project'
    | '/taxi-website-laten-maken'
    | '/webdesign-bureau'
    | '/website-laten-maken'
    | '/admin/$'
    | '/'
    | '/admin'
    | '/blog/$slug'
    | '/diensten/e-commerce'
    | '/diensten/webshops'
    | '/diensten/website-op-maat'
    | '/portfolio/$slug'
    | '/regio/$slug'
    | '/werkgebied/$slug'
    | '/blog'
    | '/diensten'
    | '/portfolio'
    | '/werkgebied'
  id:
    | '__root__'
    | '/_public'
    | '/_public/$'
    | '/_public/$landingPath'
    | '/_public/algemene-voorwaarden'
    | '/_public/bedankt'
    | '/_public/contact'
    | '/_public/cookies'
    | '/_public/gratis-website-analyse'
    | '/_public/over-ons'
    | '/_public/privacy'
    | '/_public/reviews'
    | '/_public/seo-enkhuizen'
    | '/_public/start-je-project'
    | '/_public/taxi-website-laten-maken'
    | '/_public/webdesign-bureau'
    | '/_public/website-laten-maken'
    | '/admin/$'
    | '/_public/'
    | '/admin/'
    | '/_public/blog/$slug'
    | '/_public/diensten/e-commerce'
    | '/_public/diensten/webshops'
    | '/_public/diensten/website-op-maat'
    | '/_public/portfolio/$slug'
    | '/_public/regio/$slug'
    | '/_public/werkgebied/$slug'
    | '/_public/blog/'
    | '/_public/diensten/'
    | '/_public/portfolio/'
    | '/_public/werkgebied/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminSplatRoute: typeof AdminSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/$': {
      id: '/_public/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof PublicSplatRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/$landingPath': {
      id: '/_public/$landingPath'
      path: '/$landingPath'
      fullPath: '/$landingPath'
      preLoaderRoute: typeof PublicLandingPathRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/algemene-voorwaarden': {
      id: '/_public/algemene-voorwaarden'
      path: '/algemene-voorwaarden'
      fullPath: '/algemene-voorwaarden'
      preLoaderRoute: typeof PublicAlgemeneVoorwaardenRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/bedankt': {
      id: '/_public/bedankt'
      path: '/bedankt'
      fullPath: '/bedankt'
      preLoaderRoute: typeof PublicBedanktRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cookies': {
      id: '/_public/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof PublicCookiesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gratis-website-analyse': {
      id: '/_public/gratis-website-analyse'
      path: '/gratis-website-analyse'
      fullPath: '/gratis-website-analyse'
      preLoaderRoute: typeof PublicGratisWebsiteAnalyseRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/over-ons': {
      id: '/_public/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof PublicOverOnsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reviews': {
      id: '/_public/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof PublicReviewsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/seo-enkhuizen': {
      id: '/_public/seo-enkhuizen'
      path: '/seo-enkhuizen'
      fullPath: '/seo-enkhuizen'
      preLoaderRoute: typeof PublicSeoEnkhuizenRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/start-je-project': {
      id: '/_public/start-je-project'
      path: '/start-je-project'
      fullPath: '/start-je-project'
      preLoaderRoute: typeof PublicStartJeProjectRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/taxi-website-laten-maken': {
      id: '/_public/taxi-website-laten-maken'
      path: '/taxi-website-laten-maken'
      fullPath: '/taxi-website-laten-maken'
      preLoaderRoute: typeof PublicTaxiWebsiteLatenMakenRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/webdesign-bureau': {
      id: '/_public/webdesign-bureau'
      path: '/webdesign-bureau'
      fullPath: '/webdesign-bureau'
      preLoaderRoute: typeof PublicWebdesignBureauRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/website-laten-maken': {
      id: '/_public/website-laten-maken'
      path: '/website-laten-maken'
      fullPath: '/website-laten-maken'
      preLoaderRoute: typeof PublicWebsiteLatenMakenRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/diensten/': {
      id: '/_public/diensten/'
      path: '/diensten'
      fullPath: '/diensten/'
      preLoaderRoute: typeof PublicDienstenIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/diensten/e-commerce': {
      id: '/_public/diensten/e-commerce'
      path: '/diensten/e-commerce'
      fullPath: '/diensten/e-commerce'
      preLoaderRoute: typeof PublicDienstenECommerceRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/diensten/webshops': {
      id: '/_public/diensten/webshops'
      path: '/diensten/webshops'
      fullPath: '/diensten/webshops'
      preLoaderRoute: typeof PublicDienstenWebshopsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/diensten/website-op-maat': {
      id: '/_public/diensten/website-op-maat'
      path: '/diensten/website-op-maat'
      fullPath: '/diensten/website-op-maat'
      preLoaderRoute: typeof PublicDienstenWebsiteOpMaatRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/portfolio/': {
      id: '/_public/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PublicPortfolioIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/portfolio/$slug': {
      id: '/_public/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PublicPortfolioSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/regio/$slug': {
      id: '/_public/regio/$slug'
      path: '/regio/$slug'
      fullPath: '/regio/$slug'
      preLoaderRoute: typeof PublicRegioSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/werkgebied/': {
      id: '/_public/werkgebied/'
      path: '/werkgebied'
      fullPath: '/werkgebied/'
      preLoaderRoute: typeof PublicWerkgebiedIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/werkgebied/$slug': {
      id: '/_public/werkgebied/$slug'
      path: '/werkgebied/$slug'
      fullPath: '/werkgebied/$slug'
      preLoaderRoute: typeof PublicWerkgebiedSlugRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicSplatRoute: typeof PublicSplatRoute
  PublicLandingPathRoute: typeof PublicLandingPathRoute
  PublicAlgemeneVoorwaardenRoute: typeof PublicAlgemeneVoorwaardenRoute
  PublicBedanktRoute: typeof PublicBedanktRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicCookiesRoute: typeof PublicCookiesRoute
  PublicGratisWebsiteAnalyseRoute: typeof PublicGratisWebsiteAnalyseRoute
  PublicOverOnsRoute: typeof PublicOverOnsRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicReviewsRoute: typeof PublicReviewsRoute
  PublicSeoEnkhuizenRoute: typeof PublicSeoEnkhuizenRoute
  PublicStartJeProjectRoute: typeof PublicStartJeProjectRoute
  PublicTaxiWebsiteLatenMakenRoute: typeof PublicTaxiWebsiteLatenMakenRoute
  PublicWebdesignBureauRoute: typeof PublicWebdesignBureauRoute
  PublicWebsiteLatenMakenRoute: typeof PublicWebsiteLatenMakenRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
  PublicDienstenECommerceRoute: typeof PublicDienstenECommerceRoute
  PublicDienstenWebshopsRoute: typeof PublicDienstenWebshopsRoute
  PublicDienstenWebsiteOpMaatRoute: typeof PublicDienstenWebsiteOpMaatRoute
  PublicPortfolioSlugRoute: typeof PublicPortfolioSlugRoute
  PublicRegioSlugRoute: typeof PublicRegioSlugRoute
  PublicWerkgebiedSlugRoute: typeof PublicWerkgebiedSlugRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
  PublicDienstenIndexRoute: typeof PublicDienstenIndexRoute
  PublicPortfolioIndexRoute: typeof PublicPortfolioIndexRoute
  PublicWerkgebiedIndexRoute: typeof PublicWerkgebiedIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSplatRoute: PublicSplatRoute,
  PublicLandingPathRoute: PublicLandingPathRoute,
  PublicAlgemeneVoorwaardenRoute: PublicAlgemeneVoorwaardenRoute,
  PublicBedanktRoute: PublicBedanktRoute,
  PublicContactRoute: PublicContactRoute,
  PublicCookiesRoute: PublicCookiesRoute,
  PublicGratisWebsiteAnalyseRoute: PublicGratisWebsiteAnalyseRoute,
  PublicOverOnsRoute: PublicOverOnsRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicReviewsRoute: PublicReviewsRoute,
  PublicSeoEnkhuizenRoute: PublicSeoEnkhuizenRoute,
  PublicStartJeProjectRoute: PublicStartJeProjectRoute,
  PublicTaxiWebsiteLatenMakenRoute: PublicTaxiWebsiteLatenMakenRoute,
  PublicWebdesignBureauRoute: PublicWebdesignBureauRoute,
  PublicWebsiteLatenMakenRoute: PublicWebsiteLatenMakenRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBlogSlugRoute: PublicBlogSlugRoute,
  PublicDienstenECommerceRoute: PublicDienstenECommerceRoute,
  PublicDienstenWebshopsRoute: PublicDienstenWebshopsRoute,
  PublicDienstenWebsiteOpMaatRoute: PublicDienstenWebsiteOpMaatRoute,
  PublicPortfolioSlugRoute: PublicPortfolioSlugRoute,
  PublicRegioSlugRoute: PublicRegioSlugRoute,
  PublicWerkgebiedSlugRoute: PublicWerkgebiedSlugRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
  PublicDienstenIndexRoute: PublicDienstenIndexRoute,
  PublicPortfolioIndexRoute: PublicPortfolioIndexRoute,
  PublicWerkgebiedIndexRoute: PublicWerkgebiedIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminSplatRoute: AdminSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
