// Auto-generated by scripts/generate-landing-data.mjs. Do not edit by hand.
export interface CityBenefit { h3: string; text: string; }
export interface CityRecord {
  slug: string;
  name: string;
  title: string;
  metaDescription: string;
  h1: string;
  heroSubtitle: string;
  intro: string;
  section1: { h2: string; body: string; benefits: CityBenefit[]; };
  section2H2: string;
  section3H2: string;
  section4: { h2: string; intro: string; };
  contactBlock: { h2: string; body: string; };
  internalLinks: string;
}

export const cities: CityRecord[] = [
  {
    "slug": "amsterdam",
    "name": "Amsterdam",
    "title": "Website Laten Maken Amsterdam | Snel & Pro - Nieuwblik",
    "metaDescription": "Website laten maken in Amsterdam? Nieuwblik bouwt snelle, conversiegerichte sites voor MKB. Persoonlijk contact en moderne aanpak. Vraag offerte aan.",
    "h1": "Website laten maken in Amsterdam die klanten oplevert",
    "heroSubtitle": "Ondernemen hier betekent werken in een dynamische en internationale markt. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Voor ondernemers in Amsterdam draait alles om opvallen tussen het brede een dynamische en internationale markt. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
    "section1": {
      "h2": "Waarom Amsterdamse ondernemers kiezen voor een sterke website",
      "body": "Voor ondernemers in Amsterdam draait alles om opvallen tussen het brede een dynamische en internationale markt. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
      "benefits": [
        {
          "h3": "AI gedreven aanpak",
          "text": "We zetten slimme tools in om sneller te bouwen en beter te schrijven. Jij profiteert van de tijdwinst en de kwaliteit."
        },
        {
          "h3": "Snel live",
          "text": "Wij leveren binnen enkele weken op zonder in te leveren op kwaliteit. Strakke planning en korte lijnen houden het tempo hoog."
        },
        {
          "h3": "Strategisch meedenken",
          "text": "We bouwen niet zomaar wat je vraagt, maar adviseren waar het beter kan. Jouw doel staat altijd centraal."
        }
      ]
    },
    "section2H2": "Wat je tegenkomt zonder Nieuwblik als ondernemer in Amsterdam",
    "section3H2": "Wat ondernemers zeggen over samenwerken met Nieuwblik",
    "section4": {
      "h2": "Bekijk onze recente projecten",
      "intro": "Een selectie van projecten die laten zien hoe wij ondernemers verder helpen."
    },
    "contactBlock": {
      "h2": "Klaar voor een website die werkt voor jouw bedrijf in Amsterdam?",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "rotterdam",
    "name": "Rotterdam",
    "title": "Website Laten Maken Rotterdam | Modern MKB - Nieuwblik",
    "metaDescription": "Op zoek naar webdesign in Rotterdam? Nieuwblik levert betaalbare websites die scoren in Google en bezoekers omzetten in klanten. Plan een kennismaking.",
    "h1": "Professionele website laten maken in Rotterdam",
    "heroSubtitle": "Ondernemen hier betekent werken in een no-nonsense ondernemersklimaat. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Rotterdam is een havenstad met aanpakkers mentaliteit waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
    "section1": {
      "h2": "Zo valt jouw bedrijf in Rotterdam online op",
      "body": "Rotterdam is een havenstad met aanpakkers mentaliteit waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
      "benefits": [
        {
          "h3": "Mobile first design",
          "text": "Het overgrote deel van bezoekers komt via de smartphone binnen. Wij ontwerpen daarom altijd eerst voor mobiel."
        },
        {
          "h3": "Betaalbaar maatwerk",
          "text": "Vanaf 990 euro krijg je een complete site op maat, zonder verborgen kosten. Heldere offertes voordat we starten."
        },
        {
          "h3": "Resultaatgericht",
          "text": "We meten en optimaliseren na de lancering, want een website is nooit klaar. Samen maken we hem steeds sterker."
        }
      ]
    },
    "section2H2": "Herken jij deze problemen als ondernemer in Rotterdam?",
    "section3H2": "Ervaringen van klanten die voor Nieuwblik kozen",
    "section4": {
      "h2": "Websites die wij bouwden voor ondernemers als jij",
      "intro": "Bekijk hoe we voor andere MKB klanten resultaat boekten en wat dat voor jouw bedrijf kan betekenen."
    },
    "contactBlock": {
      "h2": "Benieuwd wat Nieuwblik kan betekenen voor jouw zaak in Rotterdam?",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "den-haag",
    "name": "Den Haag",
    "title": "Website Laten Maken Den Haag | Betaalbaar - Nieuwblik",
    "metaDescription": "Een professionele website laten bouwen in Den Haag? Wij combineren strakke designs met AI gedreven ontwikkeling voor snel resultaat. Bekijk hoe.",
    "h1": "Website laten maken in Den Haag voor jouw bedrijf",
    "heroSubtitle": "Ondernemen hier betekent werken in een formele en internationale doelgroep. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Een goede website is voor MKB in Den Haag de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
    "section1": {
      "h2": "Online groeien als ondernemer in Den Haag begint hier",
      "body": "Een goede website is voor MKB in Den Haag de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
      "benefits": [
        {
          "h3": "SEO klaar opgeleverd",
          "text": "Snelle laadtijd, technische SEO en doordachte teksten zitten standaard inbegrepen. Klaar om gevonden te worden in Google."
        },
        {
          "h3": "AI gedreven aanpak",
          "text": "We zetten slimme tools in om sneller te bouwen en beter te schrijven. Jij profiteert van de tijdwinst en de kwaliteit."
        },
        {
          "h3": "Snel live",
          "text": "Wij leveren binnen enkele weken op zonder in te leveren op kwaliteit. Strakke planning en korte lijnen houden het tempo hoog."
        }
      ]
    },
    "section2H2": "Zo verschilt werken met Nieuwblik van andere bureaus in Den Haag",
    "section3H2": "Tevreden klanten vertellen over hun nieuwe website",
    "section4": {
      "h2": "Werk waar we trots op zijn",
      "intro": "Deze cases tonen onze aanpak in beeld, met dezelfde kwaliteit die wij elke ondernemer bieden."
    },
    "contactBlock": {
      "h2": "Tijd voor een nieuwe website voor jouw onderneming in Den Haag?",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "utrecht",
    "name": "Utrecht",
    "title": "Website Laten Maken Utrecht | AI Webdesign - Nieuwblik",
    "metaDescription": "Website nodig voor jouw bedrijf in Utrecht? Nieuwblik werkt voor MKB door heel Nederland met snelle oplevering en duidelijke prijzen. Start vandaag.",
    "h1": "Jouw bedrijfswebsite laten maken in Utrecht",
    "heroSubtitle": "Ondernemen hier betekent werken in een sterk groeiende dienstensector. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Voor ondernemers in Utrecht draait alles om opvallen tussen het brede een sterk groeiende dienstensector. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
    "section1": {
      "h2": "Een website die werkt voor MKB in Utrecht",
      "body": "Voor ondernemers in Utrecht draait alles om opvallen tussen het brede een sterk groeiende dienstensector. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
      "benefits": [
        {
          "h3": "Conversiegericht ontwerp",
          "text": "Elke knop, kop en sectie heeft een doel en is gericht op actie. Je website wordt een verkoper die altijd aan staat."
        },
        {
          "h3": "Persoonlijk contact",
          "text": "Je krijgt een vast aanspreekpunt dat jouw bedrijf echt leert kennen. Geen accountmanagers of callcenters, gewoon directe lijnen."
        },
        {
          "h3": "Lokale voelhorens",
          "text": "We werken al jaren met MKB in heel Nederland en weten wat lokale ondernemers nodig hebben. Geen onnodige toeters en bellen."
        }
      ]
    },
    "section2H2": "Veelvoorkomende valkuilen voor MKB in Utrecht",
    "section3H2": "Stemmen van MKB ondernemers die ons inschakelden",
    "section4": {
      "h2": "Een greep uit onze laatste opleveringen",
      "intro": "Een selectie van projecten die laten zien hoe wij ondernemers verder helpen."
    },
    "contactBlock": {
      "h2": "Laten we samen jouw online verhaal in Utrecht sterker maken",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "eindhoven",
    "name": "Eindhoven",
    "title": "Website Laten Maken Eindhoven | Snel Live - Nieuwblik",
    "metaDescription": "Webdesign bureau voor ondernemers in Eindhoven. Strategisch ontwerp, sterke teksten en goede vindbaarheid in één pakket. Ontdek wat wij doen.",
    "h1": "Modern webdesign voor ondernemers in Eindhoven",
    "heroSubtitle": "Ondernemen hier betekent werken in een innovatief MKB landschap. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Eindhoven is een tech en design hub waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
    "section1": {
      "h2": "De kracht van een professionele site voor Eindhoven",
      "body": "Eindhoven is een tech en design hub waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
      "benefits": [
        {
          "h3": "Mobile first design",
          "text": "Het overgrote deel van bezoekers komt via de smartphone binnen. Wij ontwerpen daarom altijd eerst voor mobiel."
        },
        {
          "h3": "Betaalbaar maatwerk",
          "text": "Vanaf 990 euro krijg je een complete site op maat, zonder verborgen kosten. Heldere offertes voordat we starten."
        },
        {
          "h3": "Resultaatgericht",
          "text": "We meten en optimaliseren na de lancering, want een website is nooit klaar. Samen maken we hem steeds sterker."
        }
      ]
    },
    "section2H2": "Waar het vaak misgaat bij websites in Eindhoven",
    "section3H2": "Reacties van klanten na de oplevering",
    "section4": {
      "h2": "Projecten die laten zien wat we maken",
      "intro": "Bekijk hoe we voor andere MKB klanten resultaat boekten en wat dat voor jouw bedrijf kan betekenen."
    },
    "contactBlock": {
      "h2": "Plan jouw kennismaking en groei online in Eindhoven",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "groningen",
    "name": "Groningen",
    "title": "Website Laten Maken Groningen | Conversie - Nieuwblik",
    "metaDescription": "Wil je een nieuwe website in Groningen die echt werkt? Nieuwblik bouwt sites die opvallen, klanten aantrekken en jouw merk groter maken. Bel ons.",
    "h1": "Website bouwen in Groningen, snel en betaalbaar",
    "heroSubtitle": "Ondernemen hier betekent werken in een levendige startersmarkt. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Een goede website is voor MKB in Groningen de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
    "section1": {
      "h2": "Wat een goede website betekent voor jouw bedrijf in Groningen",
      "body": "Een goede website is voor MKB in Groningen de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
      "benefits": [
        {
          "h3": "SEO klaar opgeleverd",
          "text": "Snelle laadtijd, technische SEO en doordachte teksten zitten standaard inbegrepen. Klaar om gevonden te worden in Google."
        },
        {
          "h3": "AI gedreven aanpak",
          "text": "We zetten slimme tools in om sneller te bouwen en beter te schrijven. Jij profiteert van de tijdwinst en de kwaliteit."
        },
        {
          "h3": "Snel live",
          "text": "Wij leveren binnen enkele weken op zonder in te leveren op kwaliteit. Strakke planning en korte lijnen houden het tempo hoog."
        }
      ]
    },
    "section2H2": "Het verschil dat Nieuwblik maakt voor ondernemers in Groningen",
    "section3H2": "Verhalen van ondernemers die met ons werkten",
    "section4": {
      "h2": "Het werk van Nieuwblik in beeld",
      "intro": "Deze cases tonen onze aanpak in beeld, met dezelfde kwaliteit die wij elke ondernemer bieden."
    },
    "contactBlock": {
      "h2": "Klaar voor een website die werkt voor jouw bedrijf in Groningen?",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "tilburg",
    "name": "Tilburg",
    "title": "Website Laten Maken Tilburg | Lokaal MKB - Nieuwblik",
    "metaDescription": "Moderne websites laten ontwikkelen in Tilburg. Persoonlijke aanpak, scherpe prijzen en focus op meetbaar resultaat. Vraag een gratis offerte aan.",
    "h1": "Sterke websites laten ontwerpen in Tilburg",
    "heroSubtitle": "Ondernemen hier betekent werken in een groeiend zakelijk netwerk. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Voor ondernemers in Tilburg draait alles om opvallen tussen het brede een groeiend zakelijk netwerk. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
    "section1": {
      "h2": "Slim online aanwezig zijn als ondernemer in Tilburg",
      "body": "Voor ondernemers in Tilburg draait alles om opvallen tussen het brede een groeiend zakelijk netwerk. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
      "benefits": [
        {
          "h3": "Betaalbaar maatwerk",
          "text": "Vanaf 990 euro krijg je een complete site op maat, zonder verborgen kosten. Heldere offertes voordat we starten."
        },
        {
          "h3": "Resultaatgericht",
          "text": "We meten en optimaliseren na de lancering, want een website is nooit klaar. Samen maken we hem steeds sterker."
        },
        {
          "h3": "SEO klaar opgeleverd",
          "text": "Snelle laadtijd, technische SEO en doordachte teksten zitten standaard inbegrepen. Klaar om gevonden te worden in Google."
        }
      ]
    },
    "section2H2": "Geen tijd verspillen aan trage bureaus in Tilburg",
    "section3H2": "Wat onze klanten zeggen na livegang",
    "section4": {
      "h2": "Inspiratie uit ons portfolio",
      "intro": "Een selectie van projecten die laten zien hoe wij ondernemers verder helpen."
    },
    "contactBlock": {
      "h2": "Benieuwd wat Nieuwblik kan betekenen voor jouw zaak in Tilburg?",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "almere",
    "name": "Almere",
    "title": "Website Laten Maken Almere | Mobiel - Nieuwblik",
    "metaDescription": "Website laten ontwerpen in Almere? Nieuwblik koppelt creatief design aan slimme technologie zodat jouw bedrijf online opvalt. Plan je gesprek nu.",
    "h1": "Online opvallen als ondernemer in Almere",
    "heroSubtitle": "Ondernemen hier betekent werken in een snel uitbreidend ondernemerslandschap. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Almere is een jonge groeistad waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
    "section1": {
      "h2": "Webdesign dat past bij ondernemen in Almere",
      "body": "Almere is een jonge groeistad waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
      "benefits": [
        {
          "h3": "Mobile first design",
          "text": "Het overgrote deel van bezoekers komt via de smartphone binnen. Wij ontwerpen daarom altijd eerst voor mobiel."
        },
        {
          "h3": "Betaalbaar maatwerk",
          "text": "Vanaf 990 euro krijg je een complete site op maat, zonder verborgen kosten. Heldere offertes voordat we starten."
        },
        {
          "h3": "Resultaatgericht",
          "text": "We meten en optimaliseren na de lancering, want een website is nooit klaar. Samen maken we hem steeds sterker."
        }
      ]
    },
    "section2H2": "Wat ondernemers in Almere tegenhoudt online",
    "section3H2": "Klantverhalen die laten zien wat wij doen",
    "section4": {
      "h2": "Recent opgeleverde websites",
      "intro": "Bekijk hoe we voor andere MKB klanten resultaat boekten en wat dat voor jouw bedrijf kan betekenen."
    },
    "contactBlock": {
      "h2": "Tijd voor een nieuwe website voor jouw onderneming in Almere?",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "breda",
    "name": "Breda",
    "title": "Website Laten Maken Breda | Strategisch - Nieuwblik",
    "metaDescription": "Krachtige websites voor MKB ondernemers in Breda. Snel live, mobielvriendelijk en gebouwd voor groei. Ontdek de aanpak van Nieuwblik vandaag.",
    "h1": "Een nieuwe website laten maken in Breda",
    "heroSubtitle": "Ondernemen hier betekent werken in een sterke MKB sector. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Een goede website is voor MKB in Breda de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
    "section1": {
      "h2": "Bouw aan jouw merk in Breda met een sterke site",
      "body": "Een goede website is voor MKB in Breda de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
      "benefits": [
        {
          "h3": "Resultaatgericht",
          "text": "We meten en optimaliseren na de lancering, want een website is nooit klaar. Samen maken we hem steeds sterker."
        },
        {
          "h3": "SEO klaar opgeleverd",
          "text": "Snelle laadtijd, technische SEO en doordachte teksten zitten standaard inbegrepen. Klaar om gevonden te worden in Google."
        },
        {
          "h3": "AI gedreven aanpak",
          "text": "We zetten slimme tools in om sneller te bouwen en beter te schrijven. Jij profiteert van de tijdwinst en de kwaliteit."
        }
      ]
    },
    "section2H2": "Eindelijk een bureau dat snapt wat MKB in Breda nodig heeft",
    "section3H2": "Reviews van ondernemers die kozen voor Nieuwblik",
    "section4": {
      "h2": "Een blik op onze klantprojecten",
      "intro": "Deze cases tonen onze aanpak in beeld, met dezelfde kwaliteit die wij elke ondernemer bieden."
    },
    "contactBlock": {
      "h2": "Laten we samen jouw online verhaal in Breda sterker maken",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "nijmegen",
    "name": "Nijmegen",
    "title": "Website Laten Maken Nijmegen | Online Groei - Nieuwblik",
    "metaDescription": "Een website die past bij jouw bedrijf in Nijmegen? Nieuwblik bouwt op maat, met strategie en oog voor detail. Vraag direct een offerte aan.",
    "h1": "Website op maat voor MKB in Nijmegen",
    "heroSubtitle": "Ondernemen hier betekent werken in een mix van traditie en innovatie. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Voor ondernemers in Nijmegen draait alles om opvallen tussen het brede een mix van traditie en innovatie. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
    "section1": {
      "h2": "Een website die meer doet voor jouw zaak in Nijmegen",
      "body": "Voor ondernemers in Nijmegen draait alles om opvallen tussen het brede een mix van traditie en innovatie. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
      "benefits": [
        {
          "h3": "Lokale voelhorens",
          "text": "We werken al jaren met MKB in heel Nederland en weten wat lokale ondernemers nodig hebben. Geen onnodige toeters en bellen."
        },
        {
          "h3": "Mobile first design",
          "text": "Het overgrote deel van bezoekers komt via de smartphone binnen. Wij ontwerpen daarom altijd eerst voor mobiel."
        },
        {
          "h3": "Betaalbaar maatwerk",
          "text": "Vanaf 990 euro krijg je een complete site op maat, zonder verborgen kosten. Heldere offertes voordat we starten."
        }
      ]
    },
    "section2H2": "Stop met websitezorgen, Nijmegen edition",
    "section3H2": "Eerlijke ervaringen met Nieuwblik",
    "section4": {
      "h2": "Cases die voor zich spreken",
      "intro": "Een selectie van projecten die laten zien hoe wij ondernemers verder helpen."
    },
    "contactBlock": {
      "h2": "Plan jouw kennismaking en groei online in Nijmegen",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "arnhem",
    "name": "Arnhem",
    "title": "Website Laten Maken Arnhem | Snel & Pro - Nieuwblik",
    "metaDescription": "Website laten maken in Arnhem? Nieuwblik bouwt snelle, conversiegerichte sites voor MKB. Persoonlijk contact en moderne aanpak. Vraag offerte aan.",
    "h1": "Website laten maken in Arnhem die klanten oplevert",
    "heroSubtitle": "Ondernemen hier betekent werken in een veelzijdige creatieve sector. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Arnhem is een modestad met groene insteek waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
    "section1": {
      "h2": "Waarom Arnhemse ondernemers kiezen voor een sterke website",
      "body": "Arnhem is een modestad met groene insteek waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
      "benefits": [
        {
          "h3": "Betaalbaar maatwerk",
          "text": "Vanaf 990 euro krijg je een complete site op maat, zonder verborgen kosten. Heldere offertes voordat we starten."
        },
        {
          "h3": "Resultaatgericht",
          "text": "We meten en optimaliseren na de lancering, want een website is nooit klaar. Samen maken we hem steeds sterker."
        },
        {
          "h3": "SEO klaar opgeleverd",
          "text": "Snelle laadtijd, technische SEO en doordachte teksten zitten standaard inbegrepen. Klaar om gevonden te worden in Google."
        }
      ]
    },
    "section2H2": "Wat je tegenkomt zonder Nieuwblik als ondernemer in Arnhem",
    "section3H2": "Wat ondernemers zeggen over samenwerken met Nieuwblik",
    "section4": {
      "h2": "Bekijk onze recente projecten",
      "intro": "Bekijk hoe we voor andere MKB klanten resultaat boekten en wat dat voor jouw bedrijf kan betekenen."
    },
    "contactBlock": {
      "h2": "Klaar voor een website die werkt voor jouw bedrijf in Arnhem?",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "apeldoorn",
    "name": "Apeldoorn",
    "title": "Website Laten Maken Apeldoorn | Modern MKB - Nieuwblik",
    "metaDescription": "Op zoek naar webdesign in Apeldoorn? Nieuwblik levert betaalbare websites die scoren in Google en bezoekers omzetten in klanten. Plan een kennismaking.",
    "h1": "Professionele website laten maken in Apeldoorn",
    "heroSubtitle": "Ondernemen hier betekent werken in een degelijk familiegericht ondernemersklimaat. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Een goede website is voor MKB in Apeldoorn de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
    "section1": {
      "h2": "Zo valt jouw bedrijf in Apeldoorn online op",
      "body": "Een goede website is voor MKB in Apeldoorn de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
      "benefits": [
        {
          "h3": "Mobile first design",
          "text": "Het overgrote deel van bezoekers komt via de smartphone binnen. Wij ontwerpen daarom altijd eerst voor mobiel."
        },
        {
          "h3": "Betaalbaar maatwerk",
          "text": "Vanaf 990 euro krijg je een complete site op maat, zonder verborgen kosten. Heldere offertes voordat we starten."
        },
        {
          "h3": "Resultaatgericht",
          "text": "We meten en optimaliseren na de lancering, want een website is nooit klaar. Samen maken we hem steeds sterker."
        }
      ]
    },
    "section2H2": "Herken jij deze problemen als ondernemer in Apeldoorn?",
    "section3H2": "Ervaringen van klanten die voor Nieuwblik kozen",
    "section4": {
      "h2": "Websites die wij bouwden voor ondernemers als jij",
      "intro": "Deze cases tonen onze aanpak in beeld, met dezelfde kwaliteit die wij elke ondernemer bieden."
    },
    "contactBlock": {
      "h2": "Benieuwd wat Nieuwblik kan betekenen voor jouw zaak in Apeldoorn?",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "haarlem",
    "name": "Haarlem",
    "title": "Website Laten Maken Haarlem | Betaalbaar - Nieuwblik",
    "metaDescription": "Een professionele website laten bouwen in Haarlem? Wij combineren strakke designs met AI gedreven ontwikkeling voor snel resultaat. Bekijk hoe.",
    "h1": "Website laten maken in Haarlem voor jouw bedrijf",
    "heroSubtitle": "Ondernemen hier betekent werken in een welvarend lokaal MKB. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Voor ondernemers in Haarlem draait alles om opvallen tussen het brede een welvarend lokaal MKB. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
    "section1": {
      "h2": "Online groeien als ondernemer in Haarlem begint hier",
      "body": "Voor ondernemers in Haarlem draait alles om opvallen tussen het brede een welvarend lokaal MKB. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
      "benefits": [
        {
          "h3": "Strategisch meedenken",
          "text": "We bouwen niet zomaar wat je vraagt, maar adviseren waar het beter kan. Jouw doel staat altijd centraal."
        },
        {
          "h3": "Conversiegericht ontwerp",
          "text": "Elke knop, kop en sectie heeft een doel en is gericht op actie. Je website wordt een verkoper die altijd aan staat."
        },
        {
          "h3": "Persoonlijk contact",
          "text": "Je krijgt een vast aanspreekpunt dat jouw bedrijf echt leert kennen. Geen accountmanagers of callcenters, gewoon directe lijnen."
        }
      ]
    },
    "section2H2": "Zo verschilt werken met Nieuwblik van andere bureaus in Haarlem",
    "section3H2": "Tevreden klanten vertellen over hun nieuwe website",
    "section4": {
      "h2": "Werk waar we trots op zijn",
      "intro": "Een selectie van projecten die laten zien hoe wij ondernemers verder helpen."
    },
    "contactBlock": {
      "h2": "Tijd voor een nieuwe website voor jouw onderneming in Haarlem?",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "amersfoort",
    "name": "Amersfoort",
    "title": "Website Laten Maken Amersfoort | AI Webdesign - Nieuwblik",
    "metaDescription": "Website nodig voor jouw bedrijf in Amersfoort? Nieuwblik werkt voor MKB door heel Nederland met snelle oplevering en duidelijke prijzen. Start vandaag.",
    "h1": "Jouw bedrijfswebsite laten maken in Amersfoort",
    "heroSubtitle": "Ondernemen hier betekent werken in een diverse zakelijke markt. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Amersfoort is een snelgroeiende centrumstad waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
    "section1": {
      "h2": "Een website die werkt voor MKB in Amersfoort",
      "body": "Amersfoort is een snelgroeiende centrumstad waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
      "benefits": [
        {
          "h3": "Resultaatgericht",
          "text": "We meten en optimaliseren na de lancering, want een website is nooit klaar. Samen maken we hem steeds sterker."
        },
        {
          "h3": "SEO klaar opgeleverd",
          "text": "Snelle laadtijd, technische SEO en doordachte teksten zitten standaard inbegrepen. Klaar om gevonden te worden in Google."
        },
        {
          "h3": "AI gedreven aanpak",
          "text": "We zetten slimme tools in om sneller te bouwen en beter te schrijven. Jij profiteert van de tijdwinst en de kwaliteit."
        }
      ]
    },
    "section2H2": "Veelvoorkomende valkuilen voor MKB in Amersfoort",
    "section3H2": "Stemmen van MKB ondernemers die ons inschakelden",
    "section4": {
      "h2": "Een greep uit onze laatste opleveringen",
      "intro": "Bekijk hoe we voor andere MKB klanten resultaat boekten en wat dat voor jouw bedrijf kan betekenen."
    },
    "contactBlock": {
      "h2": "Laten we samen jouw online verhaal in Amersfoort sterker maken",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "zaanstad",
    "name": "Zaanstad",
    "title": "Website Laten Maken Zaanstad | Snel Live - Nieuwblik",
    "metaDescription": "Webdesign bureau voor ondernemers in Zaanstad. Strategisch ontwerp, sterke teksten en goede vindbaarheid in één pakket. Ontdek wat wij doen.",
    "h1": "Modern webdesign voor ondernemers in Zaanstad",
    "heroSubtitle": "Ondernemen hier betekent werken in een bedrijvige regio met veel familiebedrijven. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Een goede website is voor MKB in Zaanstad de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
    "section1": {
      "h2": "De kracht van een professionele site voor Zaanstad",
      "body": "Een goede website is voor MKB in Zaanstad de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
      "benefits": [
        {
          "h3": "Persoonlijk contact",
          "text": "Je krijgt een vast aanspreekpunt dat jouw bedrijf echt leert kennen. Geen accountmanagers of callcenters, gewoon directe lijnen."
        },
        {
          "h3": "Lokale voelhorens",
          "text": "We werken al jaren met MKB in heel Nederland en weten wat lokale ondernemers nodig hebben. Geen onnodige toeters en bellen."
        },
        {
          "h3": "Mobile first design",
          "text": "Het overgrote deel van bezoekers komt via de smartphone binnen. Wij ontwerpen daarom altijd eerst voor mobiel."
        }
      ]
    },
    "section2H2": "Waar het vaak misgaat bij websites in Zaanstad",
    "section3H2": "Reacties van klanten na de oplevering",
    "section4": {
      "h2": "Projecten die laten zien wat we maken",
      "intro": "Deze cases tonen onze aanpak in beeld, met dezelfde kwaliteit die wij elke ondernemer bieden."
    },
    "contactBlock": {
      "h2": "Plan jouw kennismaking en groei online in Zaanstad",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "enschede",
    "name": "Enschede",
    "title": "Website Laten Maken Enschede | Conversie - Nieuwblik",
    "metaDescription": "Wil je een nieuwe website in Enschede die echt werkt? Nieuwblik bouwt sites die opvallen, klanten aantrekken en jouw merk groter maken. Bel ons.",
    "h1": "Website bouwen in Enschede, snel en betaalbaar",
    "heroSubtitle": "Ondernemen hier betekent werken in een sterk technisch en creatief MKB. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Voor ondernemers in Enschede draait alles om opvallen tussen het brede een sterk technisch en creatief MKB. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
    "section1": {
      "h2": "Wat een goede website betekent voor jouw bedrijf in Enschede",
      "body": "Voor ondernemers in Enschede draait alles om opvallen tussen het brede een sterk technisch en creatief MKB. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
      "benefits": [
        {
          "h3": "Snel live",
          "text": "Wij leveren binnen enkele weken op zonder in te leveren op kwaliteit. Strakke planning en korte lijnen houden het tempo hoog."
        },
        {
          "h3": "Strategisch meedenken",
          "text": "We bouwen niet zomaar wat je vraagt, maar adviseren waar het beter kan. Jouw doel staat altijd centraal."
        },
        {
          "h3": "Conversiegericht ontwerp",
          "text": "Elke knop, kop en sectie heeft een doel en is gericht op actie. Je website wordt een verkoper die altijd aan staat."
        }
      ]
    },
    "section2H2": "Het verschil dat Nieuwblik maakt voor ondernemers in Enschede",
    "section3H2": "Verhalen van ondernemers die met ons werkten",
    "section4": {
      "h2": "Het werk van Nieuwblik in beeld",
      "intro": "Een selectie van projecten die laten zien hoe wij ondernemers verder helpen."
    },
    "contactBlock": {
      "h2": "Klaar voor een website die werkt voor jouw bedrijf in Enschede?",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "den-bosch",
    "name": "Den Bosch",
    "title": "Website Laten Maken Den Bosch | Lokaal MKB - Nieuwblik",
    "metaDescription": "Moderne websites laten ontwikkelen in Den Bosch. Persoonlijke aanpak, scherpe prijzen en focus op meetbaar resultaat. Vraag een gratis offerte aan.",
    "h1": "Sterke websites laten ontwerpen in Den Bosch",
    "heroSubtitle": "Ondernemen hier betekent werken in een gemoedelijke maar ambitieuze ondernemerskring. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Den Bosch is een historische hofstad waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
    "section1": {
      "h2": "Slim online aanwezig zijn als ondernemer in Den Bosch",
      "body": "Den Bosch is een historische hofstad waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
      "benefits": [
        {
          "h3": "SEO klaar opgeleverd",
          "text": "Snelle laadtijd, technische SEO en doordachte teksten zitten standaard inbegrepen. Klaar om gevonden te worden in Google."
        },
        {
          "h3": "AI gedreven aanpak",
          "text": "We zetten slimme tools in om sneller te bouwen en beter te schrijven. Jij profiteert van de tijdwinst en de kwaliteit."
        },
        {
          "h3": "Snel live",
          "text": "Wij leveren binnen enkele weken op zonder in te leveren op kwaliteit. Strakke planning en korte lijnen houden het tempo hoog."
        }
      ]
    },
    "section2H2": "Geen tijd verspillen aan trage bureaus in Den Bosch",
    "section3H2": "Wat onze klanten zeggen na livegang",
    "section4": {
      "h2": "Inspiratie uit ons portfolio",
      "intro": "Bekijk hoe we voor andere MKB klanten resultaat boekten en wat dat voor jouw bedrijf kan betekenen."
    },
    "contactBlock": {
      "h2": "Benieuwd wat Nieuwblik kan betekenen voor jouw zaak in Den Bosch?",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "zwolle",
    "name": "Zwolle",
    "title": "Website Laten Maken Zwolle | Mobiel - Nieuwblik",
    "metaDescription": "Website laten ontwerpen in Zwolle? Nieuwblik koppelt creatief design aan slimme technologie zodat jouw bedrijf online opvalt. Plan je gesprek nu.",
    "h1": "Online opvallen als ondernemer in Zwolle",
    "heroSubtitle": "Ondernemen hier betekent werken in een degelijk groeiend ondernemerslandschap. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Een goede website is voor MKB in Zwolle de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
    "section1": {
      "h2": "Webdesign dat past bij ondernemen in Zwolle",
      "body": "Een goede website is voor MKB in Zwolle de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
      "benefits": [
        {
          "h3": "Betaalbaar maatwerk",
          "text": "Vanaf 990 euro krijg je een complete site op maat, zonder verborgen kosten. Heldere offertes voordat we starten."
        },
        {
          "h3": "Resultaatgericht",
          "text": "We meten en optimaliseren na de lancering, want een website is nooit klaar. Samen maken we hem steeds sterker."
        },
        {
          "h3": "SEO klaar opgeleverd",
          "text": "Snelle laadtijd, technische SEO en doordachte teksten zitten standaard inbegrepen. Klaar om gevonden te worden in Google."
        }
      ]
    },
    "section2H2": "Wat ondernemers in Zwolle tegenhoudt online",
    "section3H2": "Klantverhalen die laten zien wat wij doen",
    "section4": {
      "h2": "Recent opgeleverde websites",
      "intro": "Deze cases tonen onze aanpak in beeld, met dezelfde kwaliteit die wij elke ondernemer bieden."
    },
    "contactBlock": {
      "h2": "Tijd voor een nieuwe website voor jouw onderneming in Zwolle?",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "zoetermeer",
    "name": "Zoetermeer",
    "title": "Website Laten Maken Zoetermeer | Strategisch - Nieuwblik",
    "metaDescription": "Krachtige websites voor MKB ondernemers in Zoetermeer. Snel live, mobielvriendelijk en gebouwd voor groei. Ontdek de aanpak van Nieuwblik vandaag.",
    "h1": "Een nieuwe website laten maken in Zoetermeer",
    "heroSubtitle": "Ondernemen hier betekent werken in een sterke dienstverlenende sector. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Voor ondernemers in Zoetermeer draait alles om opvallen tussen het brede een sterke dienstverlenende sector. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
    "section1": {
      "h2": "Bouw aan jouw merk in Zoetermeer met een sterke site",
      "body": "Voor ondernemers in Zoetermeer draait alles om opvallen tussen het brede een sterke dienstverlenende sector. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
      "benefits": [
        {
          "h3": "Mobile first design",
          "text": "Het overgrote deel van bezoekers komt via de smartphone binnen. Wij ontwerpen daarom altijd eerst voor mobiel."
        },
        {
          "h3": "Betaalbaar maatwerk",
          "text": "Vanaf 990 euro krijg je een complete site op maat, zonder verborgen kosten. Heldere offertes voordat we starten."
        },
        {
          "h3": "Resultaatgericht",
          "text": "We meten en optimaliseren na de lancering, want een website is nooit klaar. Samen maken we hem steeds sterker."
        }
      ]
    },
    "section2H2": "Eindelijk een bureau dat snapt wat MKB in Zoetermeer nodig heeft",
    "section3H2": "Reviews van ondernemers die kozen voor Nieuwblik",
    "section4": {
      "h2": "Een blik op onze klantprojecten",
      "intro": "Een selectie van projecten die laten zien hoe wij ondernemers verder helpen."
    },
    "contactBlock": {
      "h2": "Laten we samen jouw online verhaal in Zoetermeer sterker maken",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "leiden",
    "name": "Leiden",
    "title": "Website Laten Maken Leiden | Online Groei - Nieuwblik",
    "metaDescription": "Een website die past bij jouw bedrijf in Leiden? Nieuwblik bouwt op maat, met strategie en oog voor detail. Vraag direct een offerte aan.",
    "h1": "Website op maat voor MKB in Leiden",
    "heroSubtitle": "Ondernemen hier betekent werken in een hoogopgeleide doelgroep. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Leiden is een kennis en wetenschapsstad waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
    "section1": {
      "h2": "Een website die meer doet voor jouw zaak in Leiden",
      "body": "Leiden is een kennis en wetenschapsstad waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
      "benefits": [
        {
          "h3": "Betaalbaar maatwerk",
          "text": "Vanaf 990 euro krijg je een complete site op maat, zonder verborgen kosten. Heldere offertes voordat we starten."
        },
        {
          "h3": "Resultaatgericht",
          "text": "We meten en optimaliseren na de lancering, want een website is nooit klaar. Samen maken we hem steeds sterker."
        },
        {
          "h3": "SEO klaar opgeleverd",
          "text": "Snelle laadtijd, technische SEO en doordachte teksten zitten standaard inbegrepen. Klaar om gevonden te worden in Google."
        }
      ]
    },
    "section2H2": "Stop met websitezorgen, Leiden edition",
    "section3H2": "Eerlijke ervaringen met Nieuwblik",
    "section4": {
      "h2": "Cases die voor zich spreken",
      "intro": "Bekijk hoe we voor andere MKB klanten resultaat boekten en wat dat voor jouw bedrijf kan betekenen."
    },
    "contactBlock": {
      "h2": "Plan jouw kennismaking en groei online in Leiden",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "maastricht",
    "name": "Maastricht",
    "title": "Website Laten Maken Maastricht | Snel & Pro - Nieuwblik",
    "metaDescription": "Website laten maken in Maastricht? Nieuwblik bouwt snelle, conversiegerichte sites voor MKB. Persoonlijk contact en moderne aanpak. Vraag offerte aan.",
    "h1": "Website laten maken in Maastricht die klanten oplevert",
    "heroSubtitle": "Ondernemen hier betekent werken in een internationaal georiënteerd MKB. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Een goede website is voor MKB in Maastricht de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
    "section1": {
      "h2": "Waarom Maastrichtse ondernemers kiezen voor een sterke website",
      "body": "Een goede website is voor MKB in Maastricht de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
      "benefits": [
        {
          "h3": "Strategisch meedenken",
          "text": "We bouwen niet zomaar wat je vraagt, maar adviseren waar het beter kan. Jouw doel staat altijd centraal."
        },
        {
          "h3": "Conversiegericht ontwerp",
          "text": "Elke knop, kop en sectie heeft een doel en is gericht op actie. Je website wordt een verkoper die altijd aan staat."
        },
        {
          "h3": "Persoonlijk contact",
          "text": "Je krijgt een vast aanspreekpunt dat jouw bedrijf echt leert kennen. Geen accountmanagers of callcenters, gewoon directe lijnen."
        }
      ]
    },
    "section2H2": "Wat je tegenkomt zonder Nieuwblik als ondernemer in Maastricht",
    "section3H2": "Wat ondernemers zeggen over samenwerken met Nieuwblik",
    "section4": {
      "h2": "Bekijk onze recente projecten",
      "intro": "Deze cases tonen onze aanpak in beeld, met dezelfde kwaliteit die wij elke ondernemer bieden."
    },
    "contactBlock": {
      "h2": "Klaar voor een website die werkt voor jouw bedrijf in Maastricht?",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "dordrecht",
    "name": "Dordrecht",
    "title": "Website Laten Maken Dordrecht | Modern MKB - Nieuwblik",
    "metaDescription": "Op zoek naar webdesign in Dordrecht? Nieuwblik levert betaalbare websites die scoren in Google en bezoekers omzetten in klanten. Plan een kennismaking.",
    "h1": "Professionele website laten maken in Dordrecht",
    "heroSubtitle": "Ondernemen hier betekent werken in een nuchter en betrokken ondernemersnetwerk. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Voor ondernemers in Dordrecht draait alles om opvallen tussen het brede een nuchter en betrokken ondernemersnetwerk. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
    "section1": {
      "h2": "Zo valt jouw bedrijf in Dordrecht online op",
      "body": "Voor ondernemers in Dordrecht draait alles om opvallen tussen het brede een nuchter en betrokken ondernemersnetwerk. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
      "benefits": [
        {
          "h3": "Lokale voelhorens",
          "text": "We werken al jaren met MKB in heel Nederland en weten wat lokale ondernemers nodig hebben. Geen onnodige toeters en bellen."
        },
        {
          "h3": "Mobile first design",
          "text": "Het overgrote deel van bezoekers komt via de smartphone binnen. Wij ontwerpen daarom altijd eerst voor mobiel."
        },
        {
          "h3": "Betaalbaar maatwerk",
          "text": "Vanaf 990 euro krijg je een complete site op maat, zonder verborgen kosten. Heldere offertes voordat we starten."
        }
      ]
    },
    "section2H2": "Herken jij deze problemen als ondernemer in Dordrecht?",
    "section3H2": "Ervaringen van klanten die voor Nieuwblik kozen",
    "section4": {
      "h2": "Websites die wij bouwden voor ondernemers als jij",
      "intro": "Een selectie van projecten die laten zien hoe wij ondernemers verder helpen."
    },
    "contactBlock": {
      "h2": "Benieuwd wat Nieuwblik kan betekenen voor jouw zaak in Dordrecht?",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "ede",
    "name": "Ede",
    "title": "Website Laten Maken Ede | Betaalbaar - Nieuwblik",
    "metaDescription": "Een professionele website laten bouwen in Ede? Wij combineren strakke designs met AI gedreven ontwikkeling voor snel resultaat. Bekijk hoe.",
    "h1": "Website laten maken in Ede voor jouw bedrijf",
    "heroSubtitle": "Ondernemen hier betekent werken in een toegankelijke lokale markt. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Ede is een groeigemeente met dorps karakter waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
    "section1": {
      "h2": "Online groeien als ondernemer in Ede begint hier",
      "body": "Ede is een groeigemeente met dorps karakter waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
      "benefits": [
        {
          "h3": "Mobile first design",
          "text": "Het overgrote deel van bezoekers komt via de smartphone binnen. Wij ontwerpen daarom altijd eerst voor mobiel."
        },
        {
          "h3": "Betaalbaar maatwerk",
          "text": "Vanaf 990 euro krijg je een complete site op maat, zonder verborgen kosten. Heldere offertes voordat we starten."
        },
        {
          "h3": "Resultaatgericht",
          "text": "We meten en optimaliseren na de lancering, want een website is nooit klaar. Samen maken we hem steeds sterker."
        }
      ]
    },
    "section2H2": "Zo verschilt werken met Nieuwblik van andere bureaus in Ede",
    "section3H2": "Tevreden klanten vertellen over hun nieuwe website",
    "section4": {
      "h2": "Werk waar we trots op zijn",
      "intro": "Bekijk hoe we voor andere MKB klanten resultaat boekten en wat dat voor jouw bedrijf kan betekenen."
    },
    "contactBlock": {
      "h2": "Tijd voor een nieuwe website voor jouw onderneming in Ede?",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "delft",
    "name": "Delft",
    "title": "Website Laten Maken Delft | AI Webdesign - Nieuwblik",
    "metaDescription": "Website nodig voor jouw bedrijf in Delft? Nieuwblik werkt voor MKB door heel Nederland met snelle oplevering en duidelijke prijzen. Start vandaag.",
    "h1": "Jouw bedrijfswebsite laten maken in Delft",
    "heroSubtitle": "Ondernemen hier betekent werken in een innovatief startup ecosysteem. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Een goede website is voor MKB in Delft de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
    "section1": {
      "h2": "Een website die werkt voor MKB in Delft",
      "body": "Een goede website is voor MKB in Delft de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
      "benefits": [
        {
          "h3": "SEO klaar opgeleverd",
          "text": "Snelle laadtijd, technische SEO en doordachte teksten zitten standaard inbegrepen. Klaar om gevonden te worden in Google."
        },
        {
          "h3": "AI gedreven aanpak",
          "text": "We zetten slimme tools in om sneller te bouwen en beter te schrijven. Jij profiteert van de tijdwinst en de kwaliteit."
        },
        {
          "h3": "Snel live",
          "text": "Wij leveren binnen enkele weken op zonder in te leveren op kwaliteit. Strakke planning en korte lijnen houden het tempo hoog."
        }
      ]
    },
    "section2H2": "Veelvoorkomende valkuilen voor MKB in Delft",
    "section3H2": "Stemmen van MKB ondernemers die ons inschakelden",
    "section4": {
      "h2": "Een greep uit onze laatste opleveringen",
      "intro": "Deze cases tonen onze aanpak in beeld, met dezelfde kwaliteit die wij elke ondernemer bieden."
    },
    "contactBlock": {
      "h2": "Laten we samen jouw online verhaal in Delft sterker maken",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "venlo",
    "name": "Venlo",
    "title": "Website Laten Maken Venlo | Snel Live - Nieuwblik",
    "metaDescription": "Webdesign bureau voor ondernemers in Venlo. Strategisch ontwerp, sterke teksten en goede vindbaarheid in één pakket. Ontdek wat wij doen.",
    "h1": "Modern webdesign voor ondernemers in Venlo",
    "heroSubtitle": "Ondernemen hier betekent werken in een grensoverschrijdende handelsmarkt. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Voor ondernemers in Venlo draait alles om opvallen tussen het brede een grensoverschrijdende handelsmarkt. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
    "section1": {
      "h2": "De kracht van een professionele site voor Venlo",
      "body": "Voor ondernemers in Venlo draait alles om opvallen tussen het brede een grensoverschrijdende handelsmarkt. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
      "benefits": [
        {
          "h3": "Strategisch meedenken",
          "text": "We bouwen niet zomaar wat je vraagt, maar adviseren waar het beter kan. Jouw doel staat altijd centraal."
        },
        {
          "h3": "Conversiegericht ontwerp",
          "text": "Elke knop, kop en sectie heeft een doel en is gericht op actie. Je website wordt een verkoper die altijd aan staat."
        },
        {
          "h3": "Persoonlijk contact",
          "text": "Je krijgt een vast aanspreekpunt dat jouw bedrijf echt leert kennen. Geen accountmanagers of callcenters, gewoon directe lijnen."
        }
      ]
    },
    "section2H2": "Waar het vaak misgaat bij websites in Venlo",
    "section3H2": "Reacties van klanten na de oplevering",
    "section4": {
      "h2": "Projecten die laten zien wat we maken",
      "intro": "Een selectie van projecten die laten zien hoe wij ondernemers verder helpen."
    },
    "contactBlock": {
      "h2": "Plan jouw kennismaking en groei online in Venlo",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "deventer",
    "name": "Deventer",
    "title": "Website Laten Maken Deventer | Conversie - Nieuwblik",
    "metaDescription": "Wil je een nieuwe website in Deventer die echt werkt? Nieuwblik bouwt sites die opvallen, klanten aantrekken en jouw merk groter maken. Bel ons.",
    "h1": "Website bouwen in Deventer, snel en betaalbaar",
    "heroSubtitle": "Ondernemen hier betekent werken in een mix van ambachtelijkheid en innovatie. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Deventer is een creatieve hanzestad waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
    "section1": {
      "h2": "Wat een goede website betekent voor jouw bedrijf in Deventer",
      "body": "Deventer is een creatieve hanzestad waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
      "benefits": [
        {
          "h3": "Conversiegericht ontwerp",
          "text": "Elke knop, kop en sectie heeft een doel en is gericht op actie. Je website wordt een verkoper die altijd aan staat."
        },
        {
          "h3": "Persoonlijk contact",
          "text": "Je krijgt een vast aanspreekpunt dat jouw bedrijf echt leert kennen. Geen accountmanagers of callcenters, gewoon directe lijnen."
        },
        {
          "h3": "Lokale voelhorens",
          "text": "We werken al jaren met MKB in heel Nederland en weten wat lokale ondernemers nodig hebben. Geen onnodige toeters en bellen."
        }
      ]
    },
    "section2H2": "Het verschil dat Nieuwblik maakt voor ondernemers in Deventer",
    "section3H2": "Verhalen van ondernemers die met ons werkten",
    "section4": {
      "h2": "Het werk van Nieuwblik in beeld",
      "intro": "Bekijk hoe we voor andere MKB klanten resultaat boekten en wat dat voor jouw bedrijf kan betekenen."
    },
    "contactBlock": {
      "h2": "Klaar voor een website die werkt voor jouw bedrijf in Deventer?",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "westland",
    "name": "Westland",
    "title": "Website Laten Maken Westland | Lokaal MKB - Nieuwblik",
    "metaDescription": "Moderne websites laten ontwikkelen in Westland. Persoonlijke aanpak, scherpe prijzen en focus op meetbaar resultaat. Vraag een gratis offerte aan.",
    "h1": "Sterke websites laten ontwerpen in Westland",
    "heroSubtitle": "Ondernemen hier betekent werken in een hechte agrarische en zakelijke gemeenschap. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Een goede website is voor MKB in Westland de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
    "section1": {
      "h2": "Slim online aanwezig zijn als ondernemer in Westland",
      "body": "Een goede website is voor MKB in Westland de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
      "benefits": [
        {
          "h3": "Resultaatgericht",
          "text": "We meten en optimaliseren na de lancering, want een website is nooit klaar. Samen maken we hem steeds sterker."
        },
        {
          "h3": "SEO klaar opgeleverd",
          "text": "Snelle laadtijd, technische SEO en doordachte teksten zitten standaard inbegrepen. Klaar om gevonden te worden in Google."
        },
        {
          "h3": "AI gedreven aanpak",
          "text": "We zetten slimme tools in om sneller te bouwen en beter te schrijven. Jij profiteert van de tijdwinst en de kwaliteit."
        }
      ]
    },
    "section2H2": "Geen tijd verspillen aan trage bureaus in Westland",
    "section3H2": "Wat onze klanten zeggen na livegang",
    "section4": {
      "h2": "Inspiratie uit ons portfolio",
      "intro": "Deze cases tonen onze aanpak in beeld, met dezelfde kwaliteit die wij elke ondernemer bieden."
    },
    "contactBlock": {
      "h2": "Benieuwd wat Nieuwblik kan betekenen voor jouw zaak in Westland?",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "alkmaar",
    "name": "Alkmaar",
    "title": "Website Laten Maken Alkmaar | Mobiel - Nieuwblik",
    "metaDescription": "Website laten ontwerpen in Alkmaar? Nieuwblik koppelt creatief design aan slimme technologie zodat jouw bedrijf online opvalt. Plan je gesprek nu.",
    "h1": "Online opvallen als ondernemer in Alkmaar",
    "heroSubtitle": "Ondernemen hier betekent werken in een loyaal lokaal MKB. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Voor ondernemers in Alkmaar draait alles om opvallen tussen het brede een loyaal lokaal MKB. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
    "section1": {
      "h2": "Webdesign dat past bij ondernemen in Alkmaar",
      "body": "Voor ondernemers in Alkmaar draait alles om opvallen tussen het brede een loyaal lokaal MKB. Een sterke website is daarbij geen luxe, maar pure noodzaak. Nieuwblik bouwt voor MKB door heel Nederland aan websites die conversiegericht en visueel sterk zijn. Door persoonlijk contact te combineren met een AI gedreven aanpak leveren we snel, betaalbaar en met aandacht voor detail. Of je nu net begint of jouw bestaande website een nieuwe boost wilt geven, wij denken vanaf de eerste minuut met je mee.",
      "benefits": [
        {
          "h3": "Lokale voelhorens",
          "text": "We werken al jaren met MKB in heel Nederland en weten wat lokale ondernemers nodig hebben. Geen onnodige toeters en bellen."
        },
        {
          "h3": "Mobile first design",
          "text": "Het overgrote deel van bezoekers komt via de smartphone binnen. Wij ontwerpen daarom altijd eerst voor mobiel."
        },
        {
          "h3": "Betaalbaar maatwerk",
          "text": "Vanaf 990 euro krijg je een complete site op maat, zonder verborgen kosten. Heldere offertes voordat we starten."
        }
      ]
    },
    "section2H2": "Wat ondernemers in Alkmaar tegenhoudt online",
    "section3H2": "Klantverhalen die laten zien wat wij doen",
    "section4": {
      "h2": "Recent opgeleverde websites",
      "intro": "Een selectie van projecten die laten zien hoe wij ondernemers verder helpen."
    },
    "contactBlock": {
      "h2": "Tijd voor een nieuwe website voor jouw onderneming in Alkmaar?",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "emmen",
    "name": "Emmen",
    "title": "Website Laten Maken Emmen | Strategisch - Nieuwblik",
    "metaDescription": "Krachtige websites voor MKB ondernemers in Emmen. Snel live, mobielvriendelijk en gebouwd voor groei. Ontdek de aanpak van Nieuwblik vandaag.",
    "h1": "Een nieuwe website laten maken in Emmen",
    "heroSubtitle": "Ondernemen hier betekent werken in een nuchter ondernemersklimaat. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Emmen is een ondernemende noorderling waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
    "section1": {
      "h2": "Bouw aan jouw merk in Emmen met een sterke site",
      "body": "Emmen is een ondernemende noorderling waar ondernemen energie en visie vraagt. Met de juiste online uitstraling vergroot je jouw bereik direct. Nieuwblik werkt vanuit Enkhuizen voor klanten in heel Nederland en levert websites die in lijn zijn met jouw doelen. Wij koppelen creatief design aan slimme techniek, zodat je sneller live bent zonder kwaliteitsverlies. Persoonlijk contact, transparante prijzen en een focus op meetbaar resultaat zijn vanzelfsprekend.",
      "benefits": [
        {
          "h3": "Strategisch meedenken",
          "text": "We bouwen niet zomaar wat je vraagt, maar adviseren waar het beter kan. Jouw doel staat altijd centraal."
        },
        {
          "h3": "Conversiegericht ontwerp",
          "text": "Elke knop, kop en sectie heeft een doel en is gericht op actie. Je website wordt een verkoper die altijd aan staat."
        },
        {
          "h3": "Persoonlijk contact",
          "text": "Je krijgt een vast aanspreekpunt dat jouw bedrijf echt leert kennen. Geen accountmanagers of callcenters, gewoon directe lijnen."
        }
      ]
    },
    "section2H2": "Eindelijk een bureau dat snapt wat MKB in Emmen nodig heeft",
    "section3H2": "Reviews van ondernemers die kozen voor Nieuwblik",
    "section4": {
      "h2": "Een blik op onze klantprojecten",
      "intro": "Bekijk hoe we voor andere MKB klanten resultaat boekten en wat dat voor jouw bedrijf kan betekenen."
    },
    "contactBlock": {
      "h2": "Laten we samen jouw online verhaal in Emmen sterker maken",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  },
  {
    "slug": "leeuwarden",
    "name": "Leeuwarden",
    "title": "Website Laten Maken Leeuwarden | Online Groei - Nieuwblik",
    "metaDescription": "Een website die past bij jouw bedrijf in Leeuwarden? Nieuwblik bouwt op maat, met strategie en oog voor detail. Vraag direct een offerte aan.",
    "h1": "Website op maat voor MKB in Leeuwarden",
    "heroSubtitle": "Ondernemen hier betekent werken in een betrokken regionale ondernemerskring. Nieuwblik bouwt voor jou een website die opvalt, vertrouwen wekt en klanten oplevert.",
    "intro": "Een goede website is voor MKB in Leeuwarden de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
    "section1": {
      "h2": "Een website die meer doet voor jouw zaak in Leeuwarden",
      "body": "Een goede website is voor MKB in Leeuwarden de basis voor groei. Bezoekers maken in seconden een oordeel, dus elke detail telt. Nieuwblik helpt je daar bij met websites die professioneel ogen, snel laden en bezoekers omzetten in klanten. Onze AI gedreven manier van werken maakt het traject korter en scherper geprijsd. Wij bedienen ondernemers door heel Nederland en geloven in heldere communicatie van briefing tot live.",
      "benefits": [
        {
          "h3": "Mobile first design",
          "text": "Het overgrote deel van bezoekers komt via de smartphone binnen. Wij ontwerpen daarom altijd eerst voor mobiel."
        },
        {
          "h3": "Betaalbaar maatwerk",
          "text": "Vanaf 990 euro krijg je een complete site op maat, zonder verborgen kosten. Heldere offertes voordat we starten."
        },
        {
          "h3": "Resultaatgericht",
          "text": "We meten en optimaliseren na de lancering, want een website is nooit klaar. Samen maken we hem steeds sterker."
        }
      ]
    },
    "section2H2": "Stop met websitezorgen, Leeuwarden edition",
    "section3H2": "Eerlijke ervaringen met Nieuwblik",
    "section4": {
      "h2": "Cases die voor zich spreken",
      "intro": "Deze cases tonen onze aanpak in beeld, met dezelfde kwaliteit die wij elke ondernemer bieden."
    },
    "contactBlock": {
      "h2": "Plan jouw kennismaking en groei online in Leeuwarden",
      "body": "Wij denken graag met je mee over jouw plannen. Of je nu een eerste site nodig hebt of jouw bestaande website wilt vernieuwen, neem contact op en ontdek hoe Nieuwblik bijdraagt aan jouw online groei."
    },
    "internalLinks": "Nieuwblik werkt voor ondernemers in heel Nederland. Bekijk onze diensten, scroll door ons portfolio voor inspiratie of neem direct contact op via onze contactpagina."
  }
];

export const getCityBySlug = (slug: string) => cities.find((c) => c.slug === slug);
