// Auto-generated by scripts/generate-landing-data.mjs. Do not edit by hand.
export interface LandingLink { slug: string; name: string; }

export const cityLinks: LandingLink[] = [
  {
    "slug": "amsterdam",
    "name": "Amsterdam"
  },
  {
    "slug": "rotterdam",
    "name": "Rotterdam"
  },
  {
    "slug": "den-haag",
    "name": "Den Haag"
  },
  {
    "slug": "utrecht",
    "name": "Utrecht"
  },
  {
    "slug": "eindhoven",
    "name": "Eindhoven"
  },
  {
    "slug": "groningen",
    "name": "Groningen"
  },
  {
    "slug": "tilburg",
    "name": "Tilburg"
  },
  {
    "slug": "almere",
    "name": "Almere"
  },
  {
    "slug": "breda",
    "name": "Breda"
  },
  {
    "slug": "nijmegen",
    "name": "Nijmegen"
  },
  {
    "slug": "arnhem",
    "name": "Arnhem"
  },
  {
    "slug": "apeldoorn",
    "name": "Apeldoorn"
  },
  {
    "slug": "haarlem",
    "name": "Haarlem"
  },
  {
    "slug": "amersfoort",
    "name": "Amersfoort"
  },
  {
    "slug": "zaanstad",
    "name": "Zaanstad"
  },
  {
    "slug": "enschede",
    "name": "Enschede"
  },
  {
    "slug": "den-bosch",
    "name": "Den Bosch"
  },
  {
    "slug": "zwolle",
    "name": "Zwolle"
  },
  {
    "slug": "zoetermeer",
    "name": "Zoetermeer"
  },
  {
    "slug": "leiden",
    "name": "Leiden"
  },
  {
    "slug": "maastricht",
    "name": "Maastricht"
  },
  {
    "slug": "dordrecht",
    "name": "Dordrecht"
  },
  {
    "slug": "ede",
    "name": "Ede"
  },
  {
    "slug": "delft",
    "name": "Delft"
  },
  {
    "slug": "venlo",
    "name": "Venlo"
  },
  {
    "slug": "deventer",
    "name": "Deventer"
  },
  {
    "slug": "westland",
    "name": "Westland"
  },
  {
    "slug": "alkmaar",
    "name": "Alkmaar"
  },
  {
    "slug": "emmen",
    "name": "Emmen"
  },
  {
    "slug": "leeuwarden",
    "name": "Leeuwarden"
  }
];
