// Auto-generated by scripts/generate-landing-data.mjs. Do not edit by hand.
export interface LandingLink { slug: string; name: string; }

export const industryLinks: LandingLink[] = [
  {
    "slug": "kapper",
    "name": "Kapper"
  },
  {
    "slug": "restaurant",
    "name": "Restaurant"
  },
  {
    "slug": "bouwbedrijf",
    "name": "Bouwbedrijf"
  },
  {
    "slug": "schoonheidssalon",
    "name": "Schoonheidssalon"
  },
  {
    "slug": "fysiotherapeut",
    "name": "Fysiotherapeut"
  },
  {
    "slug": "accountant",
    "name": "Accountant"
  },
  {
    "slug": "makelaar",
    "name": "Makelaar"
  },
  {
    "slug": "tandarts",
    "name": "Tandarts"
  },
  {
    "slug": "personal-trainer",
    "name": "Personal trainer"
  },
  {
    "slug": "advocaat",
    "name": "Advocaat"
  },
  {
    "slug": "interieurontwerper",
    "name": "Interieurontwerper"
  },
  {
    "slug": "fotograaf",
    "name": "Fotograaf"
  },
  {
    "slug": "schilder",
    "name": "Schilder"
  },
  {
    "slug": "loodgieter",
    "name": "Loodgieter"
  },
  {
    "slug": "elektricien",
    "name": "Elektricien"
  },
  {
    "slug": "coach",
    "name": "Coach"
  },
  {
    "slug": "therapeut",
    "name": "Therapeut"
  },
  {
    "slug": "horecabedrijf",
    "name": "Horecabedrijf"
  },
  {
    "slug": "autogarage",
    "name": "Autogarage"
  },
  {
    "slug": "bloemist",
    "name": "Bloemist"
  },
  {
    "slug": "tuinman",
    "name": "Tuinman"
  },
  {
    "slug": "kinderopvang",
    "name": "Kinderopvang"
  },
  {
    "slug": "sportschool",
    "name": "Sportschool"
  },
  {
    "slug": "boekhouder",
    "name": "Boekhouder"
  },
  {
    "slug": "architect",
    "name": "Architect"
  },
  {
    "slug": "verzekeringsadviseur",
    "name": "Verzekeringsadviseur"
  },
  {
    "slug": "dierenarts",
    "name": "Dierenarts"
  },
  {
    "slug": "evenementenbureau",
    "name": "Evenementenbureau"
  },
  {
    "slug": "reclamebureau",
    "name": "Reclamebureau"
  },
  {
    "slug": "reinigingsbedrijf",
    "name": "Reinigingsbedrijf"
  }
];
